### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dot-mike** [jayrox/vlg#1]
This is not working out of the box...
Using FreeBSD. Installed GO then:
```
go build .
./vlg

```
No virtual libs created. After hours of debugging, the script is not picking up my paths for the media.
I have two folders for one media section, script is only picking up one, example from the XML-output:
```
$ curl http://localhost:32400/library/sections/?X-Plex-Token=xxxxx
[...]
<Directory allowSync="1" art="/:/resources/movie-fanart.jpg" composite="/library/sections/1/composite/xxx" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="1" type="movie" title="Movies" agent="com.plexapp.agents.imdb" scanner="Plex Movie Scanner" language="no" uuid="76b7ec35-07bc-433e-ad06-27c1bc131024" updatedAt="1231231212" createdAt="1231231212">
<Location id="1" path="/media/movies" />
<Location id="16" path="/mnt/movies" />
</Directory>
[...]
```

what the script sees then is:
`[{Title:Movies Path:/mnt/movies ID:16 VirtualLibPath:/media/plexvlg/}]`

Please investigate and maybe write a how-to use this

**Comment by jayrox** [comment]
Ok, so from what I can see you have one Movies section that is built from two folders `/media/movies` and `/mnt/movies`

What does your config look like?

>maybe write a how-to use this

What appears to be missing from the readme?

**Comment by dot-mike** [comment]
My vlg.json:
```
{
        "hostname": "http://localhost",
        "port": 32400,
        "plextoken": "xxxxx",
        "sections": [{
                "_id": "1",
                "name": "Movies",
                "virtuallibpath": "/media/plexvlg/",
                "virtuallibpoolroot": "",
                "virtuallibpool": []
        }]
}
```

**Comment by jayrox** [comment]
I added support for multiple source folders per section.
