### ISSUE TITLE
Support for multiple mounted drives

### ISSUE THREAD

**Issue by dot-mike** [jayrox/vlg#2]
Hi,

My request is as follow:
Support for multiple drives in Linux / BSD. The drives are a part of two different pools, but mounted on two different folders. So that would create the following setup of folders:
```
/media/movies
/mnt/movies
```

In Plex both folders is added to the library. Since hard link across devices it not possible, it's not possible to have one folder where these pool symlinks to.

Maybe it can be solved with variables?
Example vlg.sjon:
```
{
        "hostname": "http://localhost",
        "port": 32400,
        "plextoken": "xxxxxxxxxxxx",
        "sections": [
                {
                        "_id": "1",
                        "name": "Movies",
                        "virtuallibpath": "$devicepath/plexvlg",
                        "virtuallibpoolroot": "$devicepath",
                        "virtuallibpool": [
                                "/media/movies/",
				"/mnt/movies"
                        ]
                }
        ]
}
```
where variable _$devicepath_ would be pulled from Plex and it contains which root folder the media is stored, can be pulled by perfoming GET request again `/library/sections` and reading `Location` from the XML.

**Comment by jayrox** [comment]
Sounds like you should create a second section in the vlg.json if you have
two different pools. The pool part is meant for the drives in that singular
pool. So as long as the folder structure is the same it can create the
empty folders as needed and the symlinks on the drives to those folders
allowing the pooled drives to properly show their content.

Plex doesn't tell you which device contains the actual content within a
pool only that the pool contains it.

**Comment by JPH71** [comment]
Hi There

What Am I doing wrong, This is my JSON File

{
    "hostname": "http://LocalHost",
    "port": 32400,
    "plextoken": "XXXXXXXXXXXXXX",
    "sections": [
        {
            "_id": "1",
            "name": "Christmas",
            "virtuallibpath": "C:\Program Files\vlg-master\Libraries\Christmas",
            "virtuallibpoolroot": "__PATH__TO__POOLED__VIRTUAL__LIBRARY__ROOT__:",
            "virtuallibpool": [
                "__POOLED__DRIVE__1__", 
                "__POOLED__DRIVE__2__"
            ]

        }
    ]
}

I also need to add other virtual libraries... do I have to create another id section for each library?

Thanks
